language: python
python:
  - "2.6"
  - "2.7"
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  - PLONE_VERSION=4.3.x
  - PLONE_VERSION=5.0.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
install:
  - sed -ie "s#p#plone-4.3.x.cfg#plone-$PLONE_VERSION.x.cfg#" travis.cfg
  - python bootstrap-buildout.py -c travis.cfg
  - bin/buildout -N -t 20 -c travis.cfg
script:
  - bin/test
  - bin/code-analysis
after_success:
  - bin/createcoverage run bin/test
  - pip install -q coveralls
  - coveralls
