language: python
python:
  - 2.7
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  - PLONE_VERSION=4.3.x SOLR_VERSION=4.10.x
  - PLONE_VERSION=5.0.x SOLR_VERSION=4.10.x
  - PLONE_VERSION=4.3.x SOLR_VERSION=5.2.x
  - PLONE_VERSION=5.0.x SOLR_VERSION=5.2.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads,solr}
install:
  - sed -ie "s/^plone-x.x.x*/plone-$PLONE_VERSION/g" travis.cfg
  - sed -ie "s/^solr-x.x.x*/solr-$SOLR_VERSION/g" travis.cfg
  - python bootstrap-buildout.py -c travis.cfg
  - bin/buildout -N -t 20 -c travis.cfg
script:
  - bin/test
  - bin/code-analysis
after_success:
  - bin/createcoverage run bin/test
  - pip install -q coveralls
  - coveralls
