language: python
python:
  - "2.6"
  - "2.7"
cache:
  directories:
  - download-cache
install:
  - mkdir -p download-cache
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - pip install -U setuptools==1.4.2
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 20 -c travis.cfg
script:
  - bin/alltests
  - bin/code-analysis
after_success:
  - bin/createcoverage run bin/alltests
  - pip install -q coveralls
  - coveralls
